-- lcm-db: {"family": "objets", "id": "harnois_blanc", "registry": "Objets", "side": "player"}
return {
    avantage = {},
    bonus = {
        acrobaties = -1,
        depl_nage = -1,
        depl_terrestre = -1,
        equilibre = -1,
        escalade = -1,
        initiative = -1,
        meca_intervention = 2,
        pen_contondant = 4,
        resi_contondant = 3,
        resi_perforant = 3,
        resi_tranchant = 3,
    },
    categorie = "arme",
    couleurTitre = "4DE04D",
    description = "le pavois est intégralement composé de métal le rendant particulièrement lourd. Porte des enchantements qui décuple la force du porteur, lui permettant de supporter un tel fardeau.\nLe pavois donne un instinct de protectecteur.",
    forge = "equilibrage_arme/inhabituel",
    icone = "Interface\\ICONS\\inv_shield_1h_kultirasquest_b_01",
    id = "harnois_blanc",
    label = "Pavois du gardien",
    tags = "Inhabituel",
    taille = 1,
}
