-- lcm-db: {"family": "jeux", "id": "traits", "registry": "Forge", "side": "mj"}
return {
    categorie = "traits",
    champs = {
        acrobaties = {
            base = 0,
            cout = 2,
            max = 4,
            min = 0,
        },
        adresse = {
            verrou = true,
        },
        age = {
            min = -10,
        },
        communication = {
            base = 0,
            cout = 2,
            max = 4,
            min = 0,
        },
        constitution = {
            verrou = true,
        },
        cosmique = {
            base = 0,
            cout = 2,
            max = 4,
            min = 0,
        },
        course = {
            base = 0,
            cout = 2,
            max = 4,
            min = 0,
        },
        crochetage = {
            base = 0,
            cout = 2,
            max = 4,
            min = 0,
        },
        defense_constitution = {
            cout = 4,
            max = 4,
            min = -4,
        },
        deguisement = {
            base = 0,
            cout = 2,
            max = 4,
            min = 0,
        },
        depl_nage = {
            base = 0,
            cout = 2,
            max = 5,
            min = -5,
        },
        depl_terrestre = {
            base = 0,
            cout = 2,
            max = 5,
            min = -5,
        },
        depl_vol = {
            min = -10,
        },
        discretion = {
            base = 0,
            cout = 2,
            max = 4,
            min = 0,
        },
        elementaire = {
            base = 0,
            cout = 2,
            max = 4,
            min = 0,
        },
        endurance = {
            base = 0,
            cout = 2,
            max = 4,
            min = 0,
        },
        equilibre = {
            base = 0,
            cout = 2,
            max = 4,
            min = 0,
        },
        escalade = {
            base = 0,
            cout = 2,
            max = 4,
            min = 0,
        },
        escamotage = {
            base = 0,
            cout = 2,
            max = 4,
            min = 0,
        },
        esprit = {
            verrou = true,
        },
        evasion = {
            base = 0,
            cout = 2,
            max = 4,
            min = 0,
        },
        existence_ame = {
            min = -10,
        },
        existence_esprit = {
            min = -10,
        },
        fatigue = {
            base = 0,
            cout = 1,
            max = 5,
            min = -5,
        },
        force = {
            verrou = true,
        },
        initiative = {
            base = 0,
            cout = 4,
            max = 5,
            min = -5,
        },
        investigation = {
            base = 0,
            cout = 2,
            max = 4,
            min = 0,
        },
        meca_attaque_simple = {
            base = 0,
            cout = 2,
            max = 4,
            min = -4,
        },
        meca_attraction = {
            base = 0,
            cout = 2,
            max = 4,
            min = -4,
        },
        meca_bouclier = {
            base = 0,
            cout = 2,
            max = 4,
            min = -4,
        },
        meca_brise_armure = {
            base = 0,
            cout = 2,
            max = 4,
            min = -4,
        },
        meca_buff = {
            base = 0,
            cout = 2,
            max = 4,
            min = -4,
        },
        meca_confusion = {
            base = 0,
            cout = 2,
            max = 4,
            min = -4,
        },
        meca_controle_mental = {
            base = 0,
            cout = 2,
            max = 4,
            min = -4,
        },
        meca_creation = {
            base = 0,
            cout = 2,
            max = 4,
            min = -4,
        },
        meca_debuff = {
            base = 0,
            cout = 2,
            max = 4,
            min = -4,
        },
        meca_deviation = {
            base = 0,
            cout = 2,
            max = 4,
            min = -4,
        },
        meca_dissipation = {
            base = 0,
            cout = 2,
            max = 4,
            min = -4,
        },
        meca_entrave = {
            base = 0,
            cout = 2,
            max = 4,
            min = -4,
        },
        meca_illusion = {
            base = 0,
            cout = 2,
            max = 4,
            min = -4,
        },
        meca_immobilisation = {
            base = 0,
            cout = 2,
            max = 4,
            min = -4,
        },
        meca_intervention = {
            base = 0,
            cout = 2,
            max = 4,
            min = -4,
        },
        meca_levitation = {
            base = 0,
            cout = 2,
            max = 4,
            min = -4,
        },
        meca_perce_armure = {
            base = 0,
            cout = 2,
            max = 4,
            min = -4,
        },
        meca_permutation = {
            base = 0,
            cout = 2,
            max = 4,
            min = -4,
        },
        meca_repulsion = {
            base = 0,
            cout = 2,
            max = 4,
            min = -4,
        },
        meca_soin = {
            base = 0,
            cout = 2,
            max = 4,
            min = -4,
        },
        mystique = {
            verrou = true,
        },
        nage = {
            base = 0,
            cout = 2,
            max = 4,
            min = 0,
        },
        niveau = {
            min = -10,
        },
        odorat_gout = {
            base = 0,
            cout = 2,
            max = 4,
            min = 0,
        },
        ouie = {
            base = 0,
            cout = 2,
            max = 4,
            min = 0,
        },
        pa = {
            base = 0,
            cout = 8,
            max = 1,
            min = -1,
        },
        pen_contondant = {
            base = 0,
            cout = 1,
            max = 4,
            min = 0,
        },
        pen_desordre = {
            base = 0,
            cout = 1,
            max = 4,
            min = 0,
        },
        pen_eau = {
            base = 0,
            cout = 1,
            max = 4,
            min = 0,
        },
        pen_esprit = {
            base = 0,
            cout = 1,
            max = 4,
            min = 0,
        },
        pen_feu = {
            base = 0,
            cout = 1,
            max = 4,
            min = 0,
        },
        pen_lumiere = {
            base = 0,
            cout = 1,
            max = 4,
            min = 0,
        },
        pen_mort = {
            base = 0,
            cout = 1,
            max = 4,
            min = 0,
        },
        pen_ombre = {
            base = 0,
            cout = 1,
            max = 4,
            min = 0,
        },
        pen_ordre = {
            base = 0,
            cout = 1,
            max = 4,
            min = 0,
        },
        pen_perforant = {
            base = 0,
            cout = 1,
            max = 4,
            min = 0,
        },
        pen_pourriture = {
            base = 0,
            cout = 1,
            max = 4,
            min = 0,
        },
        pen_terre = {
            base = 0,
            cout = 1,
            max = 4,
            min = 0,
        },
        pen_tranchant = {
            base = 0,
            cout = 1,
            max = 4,
            min = 0,
        },
        pen_vent = {
            base = 0,
            cout = 1,
            max = 4,
            min = 0,
        },
        pen_vie = {
            base = 0,
            cout = 1,
            max = 4,
            min = 0,
        },
        perception = {
            verrou = true,
        },
        pistage = {
            base = 0,
            cout = 2,
            max = 4,
            min = 0,
        },
        poids = {
            min = -10,
        },
        prise = {
            base = 0,
            cout = 2,
            max = 4,
            min = 0,
        },
        projection = {
            base = 0,
            cout = 2,
            max = 4,
            min = 0,
        },
        puissance = {
            base = 0,
            cout = 2,
            max = 4,
            min = 0,
        },
        resi_contondant = {
            base = 0,
            cout = 1,
            max = 4,
            min = -2,
        },
        resi_desordre = {
            base = 0,
            cout = 1,
            max = 4,
            min = -2,
        },
        resi_eau = {
            base = 0,
            cout = 1,
            max = 4,
            min = -2,
        },
        resi_esprit = {
            base = 0,
            cout = 1,
            max = 4,
            min = -2,
        },
        resi_feu = {
            base = 0,
            cout = 1,
            max = 4,
            min = -2,
        },
        resi_lumiere = {
            base = 0,
            cout = 1,
            max = 4,
            min = -2,
        },
        resi_mort = {
            base = 0,
            cout = 1,
            max = 4,
            min = -2,
        },
        resi_ombre = {
            base = 0,
            cout = 1,
            max = 4,
            min = -2,
        },
        resi_ordre = {
            base = 0,
            cout = 1,
            max = 4,
            min = -2,
        },
        resi_perforant = {
            base = 0,
            cout = 1,
            max = 4,
            min = -2,
        },
        resi_pourriture = {
            base = 0,
            cout = 1,
            max = 4,
            min = -2,
        },
        resi_terre = {
            base = 0,
            cout = 1,
            max = 4,
            min = -2,
        },
        resi_tranchant = {
            base = 0,
            cout = 1,
            max = 4,
            min = -2,
        },
        resi_vent = {
            base = 0,
            cout = 1,
            max = 4,
            min = -2,
        },
        resi_vie = {
            base = 0,
            cout = 1,
            max = 4,
            min = -2,
        },
        resistance = {
            base = 0,
            cout = 2,
            max = 4,
            min = 0,
        },
        sabotage = {
            base = 0,
            cout = 2,
            max = 4,
            min = 0,
        },
        sec_deplacement = {
            min = -10,
        },
        sec_expertises = {
            min = -10,
        },
        sec_fatigue = {
            min = -10,
        },
        sec_initiative = {
            min = -10,
        },
        sec_mecanique = {
            min = -10,
        },
        sec_pa = {
            min = -10,
        },
        sec_penetration = {
            min = -10,
        },
        sec_resistance = {
            min = -10,
        },
        sec_vitalite = {
            min = -10,
        },
        toucher = {
            base = 0,
            cout = 2,
            max = 4,
            min = 0,
        },
        vol_a_la_tire = {
            base = 0,
            cout = 2,
            max = 4,
            min = 0,
        },
        vue = {
            base = 0,
            cout = 2,
            max = 4,
            min = 0,
        },
    },
    description = "",
    icone = "Interface\\Icons\\INV_Misc_QuestionMark",
    id = "traits",
    label = "Traits",
    raretes = { {
            couleur = "FF8CB8",
            id = "commun",
            label = "Commun",
            points = 6,
        }, {
            couleur = "4DE04D",
            id = "inhabituel",
            label = "Inhabituel",
            points = 12,
        }, {
            couleur = "4D8CFF",
            id = "rare",
            label = "Rare",
            points = 18,
        }, {
            couleur = "FF9926",
            id = "epique",
            label = "Épique",
            points = 26,
        } },
    remplacePublie = true,
}
