-- Les actions des boutons du MJ du lanceur radial (Core/ActionsBoutons.lua).
--
-- Ecrites ici, avec leur bouton, depuis le 3 octobre 2026 : elles venaient du
-- compendium Necronicon (Actions-MJ, et Degat MJ de l'onglet systeme), importees dans Data/Genere, et le bouton
-- ne faisait que les citer. Elles n'en font plus partie : l'outil d'import les
-- ecarte (Outils/importer_necronicon.py, EN_DUR).
--
-- Ce fichier se modifie a la main, comme le reste du code. Le format est celui
-- d'une resolution : feuilles, etapes, questions, conditions (Core/Actions.lua).
-- L'identifiant (`id`) ne change pas : les jeux de choix enregistres s'y
-- rattachent. Pas d'icone ici : c'est celle du bouton (UI/Radial.lua), la
-- meme dans le lanceur et dans le composeur.

local LCM = _G.LCM
if not LCM then return end
local Definir = LCM.ActionsBoutons.Definir

Definir("degat_mj", {
    id = "degat_mj",
    label = "Dégat MJ.",
    categorie = "systeme",
    emission = true,
    feuilles = {
        {
            etapes = {
                {
                    aggregator = "",
                    amount = "",
                    announce = "",
                    callTarget = "",
                    declareTags = "",
                    hideCost = true,
                    id = "s_compose",
                    inject = "",
                    label = "Configurer l epreuve",
                    message = "",
                    nature = "",
                    note = "",
                    out = "",
                    questionsText = "Q: Type d'épreuve | single\n- Test seul | | mode=test\n- Test avec dégât | | mode=degat\nQ: Résolution | single\n- À rand (le joueur tente) | | reso=rand\n- Auto (le joueur encaisse) | | reso=auto\nQ: Nature du jet | single | showIf: var:reso == rand\n- Stat | | jetNat=stat\n- Expertise | | jetNat=expertise\nQ: Stat opposée | single | showIf: var:jetNat == stat\n- Adresse | | statNom=Adresse\n- Esprit | | statNom=Esprit\nQ: Seuil de réussite (stat) | number | seuilStat | showIf: var:jetNat == stat\nQ: Jets d'expertise proposés  —  Nom=Seuil ; Nom2=Seuil2 … | text | jetsExp | showIf: var:jetNat == expertise\nQ: Le joueur peut se raviser ? | single | showIf: var:reso == rand\n- Oui | | raviser=oui\n- Non | | raviser=non\nQ: NF (No Fatigue) — seuil ; 0 = aucun | number | nf | showIf: var:reso == rand\nQ: Fatigue perdue si réussite (avant NF) | number | coutFat | showIf: var:reso == rand\nQ: Coût PA (à Tenter) | number | coutPA\nQ: Coût PV (à Tenter) | number | coutPV\nQ: Dégât appliqué (échec / Auto) | single | showIf: var:mode == degat\n- Normal | | dmgApplied=N\n- Critique | | dmgApplied=C\nQ: Dégât normal | number | dmgN | showIf: var:mode == degat\nQ: Dégât critique | number | dmgC | showIf: var:mode == degat\nQ: Pénétrations physiques | multi | showIf: var:mode == degat\n- Tranchant | | Type Physique=Tranchant\n- Perforant | | Type Physique=Perforant\n- Contondant | | Type Physique=Contondant\nQ: Pénétrations élémentaires | multi | showIf: var:mode == degat\n- Feu | | Type Elementaire=Feu\n- Eau | | Type Elementaire=Eau\n- Air | | Type Elementaire=Air\n- Terre | | Type Elementaire=Terre\n- Esprit | | Type Elementaire=Esprit\n- Pourriture | | Type Elementaire=Pourriture\nQ: Pénétrations cosmologiques | multi | showIf: var:mode == degat\n- Lumiere | | Type Cosmologie=Lumiere\n- Ombre | | Type Cosmologie=Ombre\n- Ordre | | Type Cosmologie=Ordre\n- Désordre | | Type Cosmologie=Désordre\n- Vie | | Type Cosmologie=Vie\n- Mort | | Type Cosmologie=Mort\nQ: Sur échec — baisse de jauges  (#tag=Montant ; …) | text | failGauges | showIf: var:reso == rand\nQ: Message de réussite | text | msgOK\nQ: Message d'échec | text | msgKO",
                    sign = "-",
                    tag = "",
                    tags = "",
                    type = "compose",
                },
                {
                    aggregator = "",
                    amount = "",
                    announce = "oui",
                    callTarget = "",
                    declareTags = "Total Normal={var:dmgN} ; Total Critique={var:dmgC} ; DmgApplied={var:dmgApplied} ; Type Physique={var:Type Physique} ; Type Elementaire={var:Type Elementaire} ; Type Cosmologie={var:Type Cosmologie} ; Zones=#sante #bouclier #armure ; Perce armure=0 ; Mode={var:mode} ; Reso={var:reso} ; Raviser={var:raviser} ; JetStat={var:statNom}={var:seuilStat} ; JetExp={var:jetsExp} ; Nf={var:nf} ; CoutFat={var:coutFat} ; CoutPA={var:coutPA} ; CoutPV={var:coutPV} ; FailGauges={var:failGauges} ; MsgOK={var:msgOK} ; MsgKO={var:msgKO} ; Cout PA=0 ; Cout PF=0",
                    id = "s_dec",
                    inject = "",
                    label = "Declarer l'epreuve MJ",
                    message = "",
                    nature = "Test MJ",
                    note = "",
                    out = "",
                    questionsText = "",
                    sign = "-",
                    tag = "",
                    tags = "",
                    type = "declare",
                },
            },
            id = "s_mj",
            nom = "Epreuve MJ",
        },
    },
    natures = "Test MJ",
})

Definir("buff_debuff_mj", {
    id = "buff_debuff_mj",
    label = "Buff / Débuff MJ",
    categorie = "mj",
    debug = true,
    emission = true,
    feuilles = {
        {
            etapes = {
                {
                    aggregator = "",
                    amount = "",
                    announce = "",
                    callTarget = "",
                    declareTags = "",
                    hideCost = true,
                    id = "s_compose",
                    inject = "",
                    label = "Effet et jet du MJ",
                    message = "",
                    nature = "",
                    note = "Buff ou débuff libre du MJ : aucun coût, 9999 points dans le constructeur.",
                    out = "",
                    questionsText = "Q: Effet | single\n- Buff (bénéfique, pas d'opposition) | | effet=buff\n- Débuff (la cible peut résister avec Esprit ou Adresse) | | effet=debuff\nQ: Ton jet (résultat du rand du monstre / PNJ ; 0 = sans jet) | number | randManual\nQ: Compétence du jet | single\n- Esprit | | randSkillName=Esprit\n- Adresse | | randSkillName=Adresse",
                    sign = "-",
                    tag = "",
                    tags = "",
                    type = "compose",
                },
                {
                    branches = {
                        {
                            condition = "var:effet == buff",
                            id = "b_buff",
                            kind = "if",
                            steps = {
                                {
                                    aggregator = "",
                                    amount = "",
                                    announce = "",
                                    buffRulesText = "templateFilter: etat\nfamilies: [Cout durée] Durée Buff,Durée Débuff = 5 ; [Cout puissance] Puissance Buff,Puissance Débuff = 3 ; [Cout 3] Pen-Feu,Pen-air,Pen-contondant,Pen-désordre,Pen-eau,Pen-esprit,Pen-lumiere,Pen-mort,Pen-ombre,Pen-ordre,Pen-perforant,Pen-pourriture,Pen-terre,Pen-tranchant,Pen-vie,Force - Perce-armure,Mystique - Perce-armure,Perception - Perce-armure,Force - Brise-armure,Mystique - Brise-armure,Perception - Brise-armure,Constitution - Provocation,Esprit-Provocation,Force - Provocation,Mystique - Provocation,Constitution - Intimidation,Esprit - Intimidation,Force - Intimidation,Mystique - Intimidation = 3 ; [Cout 2] Resi-Mort,Resi-Vie,Resi-air,Resi-contondant,Resi-désordre,Resi-eau,Resi-esprit,Resi-feu,Resi-lumiere,Resi-ombre,Resi-ordre,Resi-perforant,Resi-pourriture,Resi-terre,Resi-tranchant,Initiative = 2 ; [Cout 6] Pistage,Fatigue,Cosmique,Elementaire,Investigation,Odorat-Gout,Ouie,Toucher,Vue,Acrobatie,Course,Endurance,Equilibre,Escalade,Nage,Prise,Projection,Puissance,Résistance,Crochetage,Discrétion,Déguisement,Escamotage,Evasion,Sabotage,Vol à la tire = 6 ; [Cout 5] Attaque simple,Perce-armure,Brise-armure,Bouclier,Soin,Buff,Debuff,Attraction,Communication,Répulsion,Immobilisation,Entrave,Déviation,Lévitation,Intervention,Permutation,Dissipation,Création,Confusion,Controle mental,Illusion,Terreste,Défense - Constitution,Force - Attaque,Mystique - Attaque,Perception - Attaque,Constitution - Bouclier,Constitution - Soin,Force - Bouclier,Mystique - Bouclier,Mystique - Soin,Constitution - Buff,Constitution - Debuff,Force - Debuff,Force - buff,Mystique - Buff,Mystique - Débuff,Perception - Debuff,Perception - buff,Adresse - Camouflage,Mystique - Camouflage,Perception - Camouflage,Force - Saignement,Mystique - Saignement,Perception - Saignement,Constitution - Empoisonnement,Mystique - Empoisonnement,Perception - Empoisonnement = 5 ; [Cout 15] Pa = 15 ; [Stat 5] Constitution,Force,Mystique,Perception = 5 ; [Stat 10] Adresse,Esprit = 10 ; * = 1\naffinityGood: 0.7\naffinityBad: 1\npool: 9999\npuissanceRef: Recapitulatif#puissance_buff\ndureeRef: Recapitulatif#durée_buff\ndurationBase: 1\ndurationPerPoint: 5\nstackDrainPct: 5\nstackLifeCost: 3\ndispellCost: 10\ndispellTag:",
                                    callTarget = "",
                                    declareTags = "",
                                    hideCost = true,
                                    id = "s_alloc_buff",
                                    inject = "",
                                    label = "Buff MJ (débridé)",
                                    message = "",
                                    nature = "",
                                    note = "",
                                    out = "",
                                    questionsText = "Q: Niveau du sort | single\n- Niveau 1 | | niveauSort=1\n- Niveau 2 | | niveauSort=2\n- Niveau 3 | | niveauSort=3\n- Niveau 4 | | niveauSort=4\n- Niveau 5 | | niveauSort=5\n- Niveau 6 | | niveauSort=6\nQ: Penetrations elementaires | multi | avg: penMoy @ Penetrations\n- Feu | | penTypes=Feu\n- Eau | | penTypes=Eau\n- Air | | penTypes=Air\n- Terre | | penTypes=Terre\n- Esprit | | penTypes=Esprit\n- Pourriture | | penTypes=Pourriture\nQ: Penetrations cosmologiques | multi | avg: penMoy @ Penetrations\n- Lumiere | | penTypes=Lumiere\n- Ombre | | penTypes=Ombre\n- Ordre | | penTypes=Ordre\n- Désordre | | penTypes=Désordre\n- Vie | | penTypes=Vie\n- Mort | | penTypes=Mort\nQ: Ciblage | single\n- Monocible | | cibleMode=mono\n- Multicible | | cibleMode=multi\n- Zone (AOE) | | cibleMode=aoe\n- Zone conditionnelle | | cibleMode=aoecond\nQ: Distance de la zone (yards) | single | showIf: var:cibleMode contient aoe\n- 4 yards | | aoeYards=4\n- 8 yards | | aoeYards=8\n- 12 yards | | aoeYards=12\n- 20 yards | | aoeYards=20\nQ: Type d'effet | single\n- Sans stack | | effetMode=simple\n- Avec stack | | effetMode=stack\nQ: Jauge drainée par le stack | single | showIf: var:effetMode == stack\n- Tête | | stackGauge=Tête ; stackGaugeCost=5\n- Torse | | stackGauge=Torse ; stackGaugeCost=5\n- Jambe | | stackGauge=Jambe ; stackGaugeCost=5\n- Bras | | stackGauge=Bras ; stackGaugeCost=5\n- Internes | | stackGauge=Internes ; stackGaugeCost=5\n- Fatigue | | stackGauge=Fatigue ; stackGaugeCost=5\n- Bouclier | | stackGauge=Bouclier ; stackGaugeCost=2\nQ: Nombre de stacks posés | single | showIf: var:effetMode == stack\n- 1 stack | | stackCount=1\n- 2 stacks | | stackCount=2\n- 3 stacks | | stackCount=3\n- 5 stacks | | stackCount=5\nQ: Fin du stack | single | showIf: var:effetMode == stack\n- Durée limitée (rounds) | | stackEnd=duree\n- Dispell (infini, retiré par un soin) | | stackEnd=dispell",
                                    sign = "-",
                                    tag = "",
                                    tags = "",
                                    type = "allocate",
                                },
                                {
                                    aggregator = "",
                                    amount = "",
                                    announce = "non",
                                    buffRulesText = "",
                                    callTarget = "",
                                    declareTags = "",
                                    id = "s_dec_buff",
                                    inject = "",
                                    label = "Declarer le buff",
                                    message = "",
                                    nature = "Buff",
                                    note = "",
                                    out = "",
                                    questionsText = "",
                                    sign = "-",
                                    tag = "",
                                    tags = "",
                                    type = "declare",
                                },
                            },
                        },
                        {
                            condition = "",
                            id = "b_dbf",
                            kind = "else",
                            steps = {
                                {
                                    aggregator = "",
                                    amount = "",
                                    announce = "",
                                    buffRulesText = "mode: debuff\ntemplateFilter: etat\nresistSkills: Esprit, Adresse\nfamilies: [Cout durée] Durée Buff,Durée Débuff = 5 ; [Cout puissance] Puissance Buff,Puissance Débuff = 3 ; [Cout 3] Pen-Feu,Pen-air,Pen-contondant,Pen-désordre,Pen-eau,Pen-esprit,Pen-lumiere,Pen-mort,Pen-ombre,Pen-ordre,Pen-perforant,Pen-pourriture,Pen-terre,Pen-tranchant,Pen-vie,Force - Perce-armure,Mystique - Perce-armure,Perception - Perce-armure,Force - Brise-armure,Mystique - Brise-armure,Perception - Brise-armure,Constitution - Provocation,Esprit-Provocation,Force - Provocation,Mystique - Provocation,Constitution - Intimidation,Esprit - Intimidation,Force - Intimidation,Mystique - Intimidation = 3 ; [Cout 2] Resi-Mort,Resi-Vie,Resi-air,Resi-contondant,Resi-désordre,Resi-eau,Resi-esprit,Resi-feu,Resi-lumiere,Resi-ombre,Resi-ordre,Resi-perforant,Resi-pourriture,Resi-terre,Resi-tranchant,Initiative = 2 ; [Cout 6] Pistage,Fatigue,Cosmique,Elementaire,Investigation,Odorat-Gout,Ouie,Toucher,Vue,Acrobatie,Course,Endurance,Equilibre,Escalade,Nage,Prise,Projection,Puissance,Résistance,Crochetage,Discrétion,Déguisement,Escamotage,Evasion,Sabotage,Vol à la tire = 6 ; [Cout 5] Attaque simple,Perce-armure,Brise-armure,Bouclier,Soin,Buff,Debuff,Attraction,Communication,Répulsion,Immobilisation,Entrave,Déviation,Lévitation,Intervention,Permutation,Dissipation,Création,Confusion,Controle mental,Illusion,Terreste,Défense - Constitution,Force - Attaque,Mystique - Attaque,Perception - Attaque,Constitution - Bouclier,Constitution - Soin,Force - Bouclier,Mystique - Bouclier,Mystique - Soin,Constitution - Buff,Constitution - Debuff,Force - Debuff,Force - buff,Mystique - Buff,Mystique - Débuff,Perception - Debuff,Perception - buff,Adresse - Camouflage,Mystique - Camouflage,Perception - Camouflage,Force - Saignement,Mystique - Saignement,Perception - Saignement,Constitution - Empoisonnement,Mystique - Empoisonnement,Perception - Empoisonnement = 5 ; [Cout 15] Pa = 15 ; [Stat 5] Constitution,Force,Mystique,Perception = 5 ; [Stat 10] Adresse,Esprit = 10 ; * = 1\naffinityGood: 0.7\naffinityBad: 1\npool: 9999\npuissanceRef: Recapitulatif#puissance_debuff\ndureeRef: Recapitulatif#durée_debuff\ndurationBase: 1\ndurationPerPoint: 5\nstackDrainPct: 5\nstackLifeCost: 3\ndispellCost: 10\ndispellTag:",
                                    callTarget = "",
                                    declareTags = "",
                                    hideCost = true,
                                    id = "s_alloc_debuff",
                                    inject = "",
                                    label = "Débuff MJ (débridé)",
                                    message = "",
                                    nature = "",
                                    note = "",
                                    out = "",
                                    questionsText = "Q: Niveau du sort | single\n- Niveau 1 | | niveauSort=1\n- Niveau 2 | | niveauSort=2\n- Niveau 3 | | niveauSort=3\n- Niveau 4 | | niveauSort=4\n- Niveau 5 | | niveauSort=5\n- Niveau 6 | | niveauSort=6\nQ: Penetrations elementaires | multi | avg: penMoy @ Penetrations\n- Feu | | penTypes=Feu\n- Eau | | penTypes=Eau\n- Air | | penTypes=Air\n- Terre | | penTypes=Terre\n- Esprit | | penTypes=Esprit\n- Pourriture | | penTypes=Pourriture\nQ: Penetrations cosmologiques | multi | avg: penMoy @ Penetrations\n- Lumiere | | penTypes=Lumiere\n- Ombre | | penTypes=Ombre\n- Ordre | | penTypes=Ordre\n- Désordre | | penTypes=Désordre\n- Vie | | penTypes=Vie\n- Mort | | penTypes=Mort\nQ: Ciblage | single\n- Monocible | | cibleMode=mono\n- Multicible | | cibleMode=multi\n- Zone (AOE) | | cibleMode=aoe\n- Zone conditionnelle | | cibleMode=aoecond\nQ: Distance de la zone (yards) | single | showIf: var:cibleMode contient aoe\n- 4 yards | | aoeYards=4\n- 8 yards | | aoeYards=8\n- 12 yards | | aoeYards=12\n- 20 yards | | aoeYards=20\nQ: Type d'effet | single\n- Sans stack | | effetMode=simple\n- Avec stack | | effetMode=stack\nQ: Jauge drainée par le stack | single | showIf: var:effetMode == stack\n- Tête | | stackGauge=Tête ; stackGaugeCost=5\n- Torse | | stackGauge=Torse ; stackGaugeCost=5\n- Jambe | | stackGauge=Jambe ; stackGaugeCost=5\n- Bras | | stackGauge=Bras ; stackGaugeCost=5\n- Internes | | stackGauge=Internes ; stackGaugeCost=5\n- Fatigue | | stackGauge=Fatigue ; stackGaugeCost=5\n- Bouclier | | stackGauge=Bouclier ; stackGaugeCost=2\nQ: Nombre de stacks posés | single | showIf: var:effetMode == stack\n- 1 stack | | stackCount=1\n- 2 stacks | | stackCount=2\n- 3 stacks | | stackCount=3\n- 5 stacks | | stackCount=5\nQ: Fin du stack | single | showIf: var:effetMode == stack\n- Durée limitée (rounds) | | stackEnd=duree\n- Dispell (infini, retiré par un soin) | | stackEnd=dispell",
                                    sign = "-",
                                    tag = "",
                                    tags = "",
                                    type = "allocate",
                                },
                                {
                                    aggregator = "",
                                    amount = "",
                                    announce = "non",
                                    buffRulesText = "",
                                    callTarget = "",
                                    declareTags = "",
                                    id = "s_dec_debuff",
                                    inject = "",
                                    label = "Declarer le debuff",
                                    message = "",
                                    nature = "Debuff",
                                    note = "",
                                    out = "",
                                    questionsText = "",
                                    sign = "-",
                                    tag = "",
                                    tags = "",
                                    type = "declare",
                                },
                            },
                        },
                    },
                    id = "s_switch",
                    label = "Buff ou débuff",
                    sign = "-",
                    type = "condition",
                },
            },
            id = "s_mj",
            nom = "Buff / Débuff MJ",
        },
    },
    natures = "Buff",
})

Definir("attaque_mj", {
    id = "attaque_mj",
    label = "Attaque MJ",
    categorie = "mj",
    emission = true,
    feuilles = {
        {
            etapes = {
                {
                    aggregator = "",
                    amount = "",
                    announce = "",
                    callTarget = "",
                    declareTags = "",
                    hideCost = true,
                    id = "s_compose",
                    inject = "",
                    label = "Configurer l'attaque",
                    message = "",
                    nature = "",
                    note = "Attaque libre du MJ : aucun coût. La cible réagit avec sa Défense (parade / encaissement).",
                    out = "",
                    questionsText = "Q: Dégât normal | number | dmgN\nQ: Dégât critique | number | dmgC\nQ: Perce-armure (part des dégâts qui ignore l'armure ; 0 = aucune) | number | perceArmure\nQ: Stat de l'attaque (ce que la cible opposera) | single\n- Adresse | | RandNom=Adresse\n- Esprit | | RandNom=Esprit\nQ: Rand de l'attaquant (ton jet, comparé au rand de la cible) | number | randRes\nQ: Pénétrations physiques | multi\n- Tranchant | | Type Physique=Tranchant\n- Perforant | | Type Physique=Perforant\n- Contondant | | Type Physique=Contondant\nQ: Pénétrations élémentaires | multi\n- Feu | | Type Elementaire=Feu\n- Eau | | Type Elementaire=Eau\n- Air | | Type Elementaire=Air\n- Terre | | Type Elementaire=Terre\n- Esprit | | Type Elementaire=Esprit\n- Pourriture | | Type Elementaire=Pourriture\nQ: Pénétrations cosmologiques | multi\n- Lumiere | | Type Cosmologie=Lumiere\n- Ombre | | Type Cosmologie=Ombre\n- Ordre | | Type Cosmologie=Ordre\n- Désordre | | Type Cosmologie=Désordre\n- Vie | | Type Cosmologie=Vie\n- Mort | | Type Cosmologie=Mort",
                    sign = "-",
                    tag = "",
                    tags = "",
                    type = "compose",
                },
                {
                    aggregator = "",
                    amount = "",
                    announce = "non",
                    callTarget = "",
                    declareTags = "Cout PA=0 ; Cout PF=0 ; Total Normal={var:dmgN} ; Total Critique={var:dmgC} ; Type Physique={var:Type Physique} ; Type Elementaire={var:Type Elementaire} ; Type Cosmologie={var:Type Cosmologie} ; Type action=Attaque MJ ; Rand Nom={var:RandNom} ; Rand Résultat={var:randRes} ; Perce armure={var:perceArmure} ; Zones=#sante #bouclier #armure",
                    id = "s_dec",
                    inject = "",
                    label = "Déclarer l'attaque MJ",
                    message = "",
                    nature = "Attaque",
                    note = "",
                    out = "",
                    questionsText = "",
                    sign = "-",
                    tag = "",
                    tags = "",
                    type = "declare",
                },
            },
            id = "s_mj",
            nom = "Attaque MJ",
        },
    },
    natures = "Attaque",
})
