-- Creation de personnage : budgets, plafonds, refus.
local function dire(...) print(table.concat({...}, " ")) end
local ko = 0
local function attendu(libelle, obtenu, voulu)
    local ok = tostring(obtenu) == tostring(voulu)
    if not ok then ko = ko + 1 end
    dire(ok and "  ok  " or "  KO  ", libelle, "=", tostring(obtenu), ok and "" or ("(attendu " .. tostring(voulu) .. ")"))
end

__declencher("PLAYER_LOGIN")
local C = LCM.Creation
local E = LCM.Equilibrage

dire("== un brouillon neuf demarre au niveau 5")
local b = C.Nouveau()
attendu("niveau de depart", b.niveau, 5)
attendu("rien de depense", C.Depense(b, "primaires"), 0)

dire("== les budgets au niveau 5")
attendu("primaires  17 + 3x5", C.Total(b, "primaires"), 32)
attendu("secondaires 12 + 4x5", C.Total(b, "secondaires"), 32)
attendu("expertises  8 + 2x5", C.Total(b, "expertises"), 18)
attendu("mecaniques  2 + 3x5", C.Total(b, "mecaniques"), 17)
attendu("traits      2 + 5/5", C.Total(b, "traits"), 3)

dire("== plafond d'une statistique primaire : 4 + niveau")
attendu("plafond", C.Plafond(b, "primaires", "force"), 9)
attendu("9 passe", (C.Definir(b, "primaires", "force", 9)), true)
local ok, raison = C.Definir(b, "primaires", "mystique", 10)
attendu("10 refuse", ok, false)
attendu("et le refus s'explique", tostring(raison):find("plafond") ~= nil, true)
attendu("la valeur refusee n'est pas ecrite", C.Valeur(b, "mystique"), 0)

dire("== le budget primaire s'epuise")
C.Definir(b, "primaires", "mystique", 9)
C.Definir(b, "primaires", "perception", 9)
attendu("depense 27 sur 32", C.Depense(b, "primaires"), 27)
attendu("reste 5", C.Budget(b, "primaires").reste, 5)

dire("== Adresse et Esprit coutent deux points et plafonnent plus bas")
attendu("cout d'une primaire ordinaire", C.Cout("primaires", "force"), 1)
attendu("cout de l'adresse", C.Cout("primaires", "adresse"), 2)
attendu("plafond de l'adresse : 2 + niveau", C.Plafond(b, "primaires", "adresse"), 7)
attendu("plafond de l'esprit", C.Plafond(b, "primaires", "esprit"), 7)
ok, raison = C.Definir(b, "primaires", "adresse", 7)
attendu("7 refuse, faute de points", ok, false)
attendu("le refus compte les points", tostring(raison):find("reste") ~= nil, true)
-- 5 points restants, 2 par cran : deux crans.
attendu("le maximum atteignable", C.Maximum(b, "primaires", "adresse"), 2)
attendu("2 passe", (C.Definir(b, "primaires", "adresse", 2)), true)
attendu("quatre points depenses pour deux crans", C.Budget(b, "primaires").reste, 1)

dire("== R et M : remettre a zero, monter au maximum")
attendu("remise a zero", (C.Remettre(b, "primaires", "adresse")), true)
attendu("les points reviennent", C.Budget(b, "primaires").reste, 5)
C.Definir(b, "primaires", "adresse", C.Maximum(b, "primaires", "adresse"))
attendu("M pose deux crans", C.Valeur(b, "adresse"), 2)
C.RemettreCategorie(b, "primaires")
attendu("la categorie entiere revient", C.Budget(b, "primaires").reste, 32)
attendu("et les valeurs sont parties", C.Valeur(b, "force"), 0)

dire("== penetration : l'exemple de l'utilisateur (3 + 3 + 3)")
local p = C.Nouveau()
C.Definir(p, "primaires", "force", 3)
C.Definir(p, "primaires", "mystique", 3)
C.Definir(p, "primaires", "perception", 3)
-- 9 / 1,75 = 5,14 arrondi a 5, plus la base de 3.
attendu("plafond d'un type", C.Plafond(p, "penetration", "pen_tranchant"), 8)
attendu("8 passe", (C.Definir(p, "penetration", "pen_tranchant", 8)), true)
attendu("9 refuse", (C.Definir(p, "penetration", "pen_perforant", 9)), false)

dire("== plus on investit en degats, plus on peut se specialiser")
attendu("sans statistique", C.Plafond(C.Nouveau(), "penetration", "pen_feu"), 3)
local fort = C.Nouveau()
C.Definir(fort, "primaires", "force", 9)
C.Definir(fort, "primaires", "mystique", 9)
attendu("avec 18 points de degats", C.Plafond(fort, "penetration", "pen_feu"), 13)

dire("== resistance : constitution / 4")
local r = C.Nouveau()
attendu("sans constitution", C.Plafond(r, "resistance", "resi_feu"), 3)
C.Definir(r, "primaires", "constitution", 4)
attendu("avec 4 de constitution", C.Plafond(r, "resistance", "resi_feu"), 4)
C.Definir(r, "primaires", "constitution", 9)
attendu("avec 9 de constitution", C.Plafond(r, "resistance", "resi_feu"), 5)

dire("== les points secondaires ne coutent pas tous pareil")
local s = C.Nouveau()
attendu("un point d'action coute 8", (C.Definir(s, "secondaires", "sec_pa", 1)), true)
attendu("depense", C.Depense(s, "secondaires"), 8)
attendu("plafond PA a 5 : 1 + 5/3", C.Plafond(s, "secondaires", "sec_pa"), 2)
attendu("3 refuse", (C.Definir(s, "secondaires", "sec_pa", 3)), false)
attendu("plafond vitalite : 2 x niveau", C.Plafond(s, "secondaires", "sec_vitalite"), 10)
attendu("plafond initiative : 4 x niveau", C.Plafond(s, "secondaires", "sec_initiative"), 20)

dire("== investir en Expertises agrandit le budget d'expertises")
local x = C.Nouveau()
attendu("budget de base", C.Total(x, "expertises"), 18)
C.Definir(x, "secondaires", "sec_expertises", 4)
attendu("quatre points secondaires = huit d'expertise", C.Total(x, "expertises"), 26)
attendu("plafond d'une expertise : 5 + niveau", C.Plafond(x, "expertises", "escalade"), 10)
attendu("11 refuse", (C.Definir(x, "expertises", "escalade", 11)), false)
attendu("10 passe", (C.Definir(x, "expertises", "escalade", 10)), true)

dire("== baisser une statistique fait deborder un type deja rempli")
local d = C.Nouveau()
C.Definir(d, "primaires", "force", 9)
C.Definir(d, "penetration", "pen_tranchant", 8)
attendu("rien ne deborde", #C.Debordements(d), 0)
C.Definir(d, "primaires", "force", 0)
local debordements = C.Debordements(d)
attendu("un debordement signale", #debordements, 1)
attendu("  la ligne", debordements[1].label, "Tranchant")
attendu("  son nouveau plafond", debordements[1].plafond, 3)
attendu("il bloque la creation", #C.Problemes(d) > 0, true)

dire("== les traits coutent de 1 a 4 points")
local t = C.Nouveau()
attendu("budget de traits", C.Budget(t, "traits").total, 3)
attendu("le trait d'exemple coute 2", LCM.Traits.Get("escalade_jungle").cout, 2)
attendu("pris", (C.AjouterTrait(t, "escalade_jungle")), true)
attendu("reste 1", C.Budget(t, "traits").reste, 1)
attendu("deux fois le meme : refuse", (C.AjouterTrait(t, "escalade_jungle")), false)
attendu("trait inconnu : refuse", (C.AjouterTrait(t, "ne_existe_pas")), false)
attendu("retire", (C.RetirerTrait(t, "escalade_jungle")), true)
attendu("budget rendu", C.Budget(t, "traits").reste, 3)
local ok2 = pcall(LCM.Traits.Add, { id = "trop_cher", label = "Trop cher", cout = 5 })
attendu("un trait a 5 points est refuse au chargement", ok2, false)

dire("== mecaniques de competence")
local m = C.Nouveau()
attendu("vingt-et-une mecaniques", #C.Lignes("mecaniques"), 21)
attendu("budget 2 + 3x5", C.Budget(m, "mecaniques").total, 17)
C.Definir(m, "secondaires", "sec_mecanique", 4)
attendu("quatre points secondaires = quatre de plus", C.Total(m, "mecaniques"), 21)
attendu("plafond, comme une expertise", C.Plafond(m, "mecaniques", "meca_soin"), 10)
attendu("11 refuse", (C.Definir(m, "mecaniques", "meca_soin", 11)), false)
attendu("10 passe", (C.Definir(m, "mecaniques", "meca_soin", 10)), true)
attendu("depense comptee", C.Budget(m, "mecaniques").depense, 10)
attendu("la repulsion existe", LCM.Schema.Field("meca_repulsion").label, "Répulsion")

dire("== un brouillon incomplet ne cree rien")
local n = C.Nouveau()
attendu("sans nom ni race", #C.Problemes(n), 2)
attendu("creation refusee", (C.Appliquer(n)), nil)

dire("== creation complete")
local final = C.Nouveau()
final.nom = "Ysolde"
final.race = "humain"
C.Definir(final, "primaires", "constitution", 6)
C.Definir(final, "secondaires", "sec_vitalite", 4)
C.Definir(final, "expertises", "escalade", 3)
C.Definir(final, "penetration", "pen_tranchant", 3)
C.AjouterTrait(final, "escalade_jungle")
attendu("aucun probleme", #C.Problemes(final), 0)
local entity = C.Appliquer(final)
attendu("personnage cree", entity ~= nil, true)
attendu("il est joue", LCM.Personnages.ActifId(), entity.id)
attendu("sa race", LCM.Entities.Get_Value(entity, "race"), "humain")
attendu("son niveau", LCM.Entities.Get_Value(entity, "niveau"), 5)
attendu("sa constitution", LCM.Entities.Get_Value(entity, "constitution"), 6)
attendu("sa vitalite", LCM.Entities.Get_Value(entity, "sec_vitalite"), 4)
attendu("sa penetration tranchante", LCM.Entities.Get_Value(entity, "pen_tranchant"), 3)
attendu("son trait", LCM.Traits.Has(entity, "escalade_jungle"), true)
-- PV = 2 + 1,5x5 + 0,25x6 + 3x4 = 23
attendu("ses PV max", LCM.Entities.Get_Value(entity, "pv_max"), 23)

dire("== ce qui vaut le defaut n'est pas sauvegarde")
local ecrits = 0
for _ in pairs(entity.values) do ecrits = ecrits + 1 end
dire("   " .. ecrits .. " valeurs ecrites sur " .. LCM.Schema.Count() .. " champs")
attendu("le niveau de depart n'est pas stocke", entity.values.niveau, nil)

dire(ko == 0 and "TOUT PASSE" or (ko .. " ECHEC(S)"))
